### PR TITLE
fix!: fix error parsing platform and configuration

### LINKED ISSUE #21: [BUG]: Support solution configuration names other than just Debug and Release
### Description of the feature/enhancement

Hi.

Thank you for SlnParser.

When I try to parse a sln file which contains a solution configuration name other than "Debug" or "Release", I get the following exception:

```
SlnParser.Contracts.Exceptions.ParseSolutionFailedException: Could not parse provided Solution 'C:\Work\Team\dev\Test.sln'. See inner exception for more information ---> SlnParser.Contracts.Exceptions.UnexpectedSolutionStructureException: Default is not recognized as a possible value for BuildConfiguration

Stack Trace: 
SolutionConfigurationPlatformParser.ParseBuildConfiguration(String buildConfigurationString)
SolutionConfigurationPlatformParser.ParseConfigurationPlatformFromMatch(Match match)
SolutionConfigurationPlatformParser.ParseConfigurationPlatform(String line)
<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
SelectListIterator`2.ToList()
EnrichSolutionWithSolutionConfigurationPlatforms.Enrich(Solution solution, IEnumerable`1 fileContents)
SolutionParser.ParseInternal(FileInfo solutionFile)
SolutionParser.Parse(FileInfo solutionFile)
--- End of inner exception stack trace ---
SolutionParser.Parse(FileInfo solutionFile)
SolutionParser.Parse(String solutionFileName)
```

Solution configuration names can be anything (see below) and so I didn't expect `BuildConfiguration` to be an `enum`.

image

There's also a similar issue for `BuildPlatform`.
For example, `BuildPlatform` doesn't support `Mixed Platforms`, `Win32`, or any other custom name, and I didn't expect it to be an `enum` either.

image

Instead, I expected those properties of `ConfigurationPlatform` to be of a `string` data type.

Thank you.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by wgnf**
## 📫 Addressed Issue(s)

- Closes #21

## 📄 Description

This fixes an issue report by @icnocop, which happened, because build-configuration and -platform were defined as having only a set of values. With that, an enum was used. This does not work in the real world though, because above mentioned configurations can have any user defined value.

## ✅ Checks

- [x] My PR adheres to the general code-style of this project (look at other code if you're unsure)
- ~[ ] My code requires changes to the documentation~
- ~[ ] I have updated the documentation as required~
- [x] All the automated tests have passed

## ℹ Additional Information

-

### CODE REVIEW

File: src/SlnParser/Contracts/BuildConfigurationDefaults.cs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+        /// <summary>
+        ///     The release configuration
+        /// </summary>
+        public const string Release = "Release";
+
+        /// <summary>
+        ///     The default configuration
+        /// </summary>
+        public const string Default = "Default";
```
Comment (icnocop) [inline src/SlnParser/Contracts/BuildConfigurationDefaults.cs:21]: I don't see where this is used

File: src/SlnParser/Contracts/BuildPlatformDefaults.cs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+        
+        /// <summary>
+        ///     Only Windows 32 platforms are targeted
+        /// </summary>
+        public const string Win32 = "Win32";
+
+        /// <summary>
+        ///     Only Windows 7 platforms are targeted
+        /// </summary>
+        public const string Win7 = "Win7";
```
Comment (icnocop) [inline src/SlnParser/Contracts/BuildPlatformDefaults.cs:36]: I don't see where this is used.

File: src/SlnParser/Contracts/BuildPlatformDefaults.cs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+        
+        /// <summary>
+        ///     Only x86 (32 bit) CPU-platforms are targeted
+        /// </summary>
+        public const string X86 = "x86";
+        
+        /// <summary>
+        ///     There is a mix of different platforms that are targeted
+        /// </summary>
+        public const string MixedPlatforms = "Mixed Platforms";
```
Comment (icnocop) [inline src/SlnParser/Contracts/BuildPlatformDefaults.cs:26]: I don't see where this is used.

File: src/SlnParser/Contracts/BuildPlatformDefaults.cs [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+        
+        /// <summary>
+        ///     Only Windows 32 platforms are targeted
+        /// </summary>
+        public const string Win32 = "Win32";
```
Comment (icnocop) [inline src/SlnParser/Contracts/BuildPlatformDefaults.cs:31]: I don't see where this is used.

**Review by icnocop — APPROVED** [review]
I found some unused fields (not a big deal).

Other than that, it works as expected.

Thank you! 🎉

**Comment by wgnf** [comment]
I added those to maybe help other users, when they need some defaults.

Or do you think this might not be needed?

File: src/SlnParser/Contracts/BuildConfigurationDefaults.cs (hunk 1 above)
Comment (wgnf) [reply src/SlnParser/Contracts/BuildConfigurationDefaults.cs:21]: Just thought this might be a helpful thing to have for users, if they went to check certain things. Let me know if this might not be needed though.

**Comment by icnocop** [comment]
I don't think they're needed.

The two new classes are only currently used in `IntegrationTests.cs`, so I don't think they should be part of the public contract.

Thank you.

**Comment by wgnf** [comment]
Thank you for your feedback, I just removed those classes.

**Review by icnocop — APPROVED** [review]

**Comment by icnocop** [comment]
Yes, it looks good. Thank you!

**Comment by wgnf** [comment]
Included in version `3.0.0` that has just been released (also see https://github.com/wgnf/SlnParser/releases/tag/v3.0.0). Thanks a lot @icnocop!
